@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
  BackgroundColor #FDF6E3
  BorderColor Black
  ArrowColor Black
}

actor Tutor as T
actor Alumno as AL
actor Profesor as P
actor "Control Escolar" as CE
actor Administrador as A
actor "tesorero/admin" as Cuentas

rectangle "Sistema de Gestión Escolar Primaria" {

  package "Control_de_Pagos_de_Colegiatura" {
  usecase "Buscar alumno" as UC50
  usecase "Consultar_historial de pagos" as UC51
  usecase "Registrar pago mensual" as UC52
  usecase "Actualizar estatus de pago" as UC53
  usecase "Generar recibo de pago" as UC54
  usecase "Consultar mi historial de pago" as UC55
   }

  package "Control de Calificaciones" {
    usecase "Ver Historial de Calificaciones" as UC1000
    usecase "Registrar Calificaciones" as UC1100
    usecase "Consultar Calificaciones" as UC1200
    usecase "Modificar Calificaciones" as UC1300
    usecase "Exportar Calificaciones" as UC1400
    usecase "Cerrar Perioo de Captura" as UC101500
    usecase "Consultar Validar Datos Herroneos" as UC1016
  }

  package "Control de Asistencia" {
    usecase "Registrar Asistencia" as UC8
    usecase "Consultar Asistencia" as UC9
    usecase "Justificar Asistencia" as UC24
  }

  package "Control de actividades / tareas" {
    usecase "Crear actidad" as UC15
    usecase "Asignar actividad" as UC16
    usecase "Calificar actividad" as UC17
  }

  package "Control/Gestion de Grupos Escolares" {
   
  usecase "Asignar alumnos a Grupo" as UC101
  usecase "Asignar profesor a grupo" as UC202
  usecase "Asignar horario a grupo" as UC303
  usecase "Asignar salon a grupo"  as UC404 
  usecase "Crear grupo" as UC5
  }

  package "Gestión de Información de Usuarios" {
    usecase "Registrar usuario" as UC1
    usecase "Modificar Datos del usuario" as UC2
    usecase "Dar de Baja usuario" as UC3
    usecase "Consultar Datos del usuario" as UC4
  }

  package "Control de Materias" {
    usecase "Crear materia" as UC21
    usecase "asignar materia a grupo" as UC22
    usecase "eliminar materia" as UC23
  }

  package "Notificación" {
    usecase "Crear notificación" as UC18
    usecase "Enviar notificación" as UC19
    usecase "Ver notificaciones" as UC20
  }
}

' Relaciones con actores

@enduml
