@startuml  Control_Asistencia
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
  BackgroundColor #FDF6E3
  BorderColor Black
  ArrowColor Black
}

actor "Alumno" as A
actor "Profesor" as CE
actor "Tutor" as T

rectangle "Control de Asistencia" {
  usecase "Ver Asistencia" as UC1
  usecase "Justificar Asistencia" as UC2
  usecase "Modificar la Lista" as UC3
  usecase "Publicar Lista de mi Grupo"  as UC4 

}

'Profesor 
CE-->UC1

CE-->UC3  
CE-->UC4
 
 'Alumno
 A-->UC1

 'Tutor
 T-->UC1
 T-->UC2
